apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-app
  namespace: laravel-k8s
  labels:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - k8s.api
      secretName: nginx-ingress-secret
  rules:
    - host: k8s.api
      http:
        paths:
          - path:
            backend:
              serviceName: frontend-service
              servicePort: 80


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-http
  namespace: laravel-k8s
spec:
  rules:
    - host: k8s.wp53.com
      http:
        paths:
          - path:
            backend:
              serviceName: frontend-service
              servicePort: 80