apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-app
  namespace: laravel-k8s
  labels:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    # 定义域名
    - host: k8s.api
      http:
        paths:
          # 不同path转发到不同端口
          - path:
            backend:
              serviceName: frontend-service
              servicePort: 80
